# --------- Logs ---------------
log_root: ./logs

# --------- Data ---------------
dataset_name: hoskinson-center/minif2f-lean4
split: validation
slice_size: null

# ---------- Model ------------
model_name: wellecks/llmstep-mathlib4-pythia2.8b

# ---------- Search Method ----------
# Choose from simple_search, best_first_search, mcts, rir
# Can be overwrite by the command line argument
search_method: best_first_search

# ---------- Args for simple first search  ----------
search_budget: 32

# ---------- Args for best first search  ----------
max_iters: 100
temperatures: 
  - 0.0
num_samples: 32
verbose: true

# ---------- Args for mcts search  ----------

# ---------- Args for bilevel mcts search  ----------

