# --------- Logs ---------------
log_root: ./logs

# --------- Data ---------------
dataset_name: hoskinson-center/minif2f-lean4
split: test
slice_size: 1

# ---------- Model ------------
model_name: open-web-math/llemma_7b

# ---------- Search Method ----------
search_method: simple_search
# Choose from simple_search, best_first_search, mcts, rir

# ---------- Args for simple first search  ----------
search_budget: 10

# ---------- Args for best first search  ----------
max_iters: 10
temperatures: 
  - 0.5
num_samples: 4
verbose: true

# ---------- Args for mcts search  ----------

# ---------- Args for bilevel mcts search  ----------

